"""
Render parsed commits into release notes (Markdown or plain text).
"""

from __future__ import annotations

import json
from datetime import date
from typing import Literal

from .parser import Commit

SECTION_ORDER = [
    ("breaking", "BREAKING CHANGES"),
    ("feat", "New Features"),
    ("fix", "Bug Fixes"),
    ("perf", "Performance Improvements"),
    ("refactor", "Refactoring"),
    ("docs", "Documentation"),
    ("build", "Build System"),
    ("ci", "CI/CD"),
    ("test", "Tests"),
    ("chore", "Chores"),
    ("other", "Other Changes"),
]


def _group_commits(commits: list[Commit]) -> dict[str, list[Commit]]:
    groups: dict[str, list[Commit]] = {k: [] for k, _ in SECTION_ORDER}

    for c in commits:
        if c.breaking:
            groups["breaking"].append(c)
        key = c.commit_type if c.commit_type in groups else "other"
        if not c.breaking or key != "feat":  # avoid double-listing breaking feats
            groups[key].append(c)

    return groups


def render_markdown(
    commits: list[Commit],
    version: str,
    repo_url: str | None = None,
) -> str:
    today = date.today().isoformat()
    groups = _group_commits(commits)

    lines = [f"# Release {version} — {today}", ""]

    has_content = False
    for key, title in SECTION_ORDER:
        section_commits = groups.get(key, [])
        if not section_commits:
            continue
        has_content = True
        lines.append(f"## {title}")
        lines.append("")
        for c in section_commits:
            scope = f"**{c.scope}**: " if c.scope else ""
            issue_links = ""
            if c.issues and repo_url:
                issue_links = " (" + ", ".join(
                    f"[{i}]({repo_url}/issues/{i.lstrip('#')})" for i in c.issues
                ) + ")"
            elif c.issues:
                issue_links = " (" + ", ".join(c.issues) + ")"

            hash_link = (
                f"[`{c.short_hash}`]({repo_url}/commit/{c.hash})"
                if repo_url
                else f"`{c.short_hash}`"
            )
            lines.append(f"- {scope}{c.subject}{issue_links} {hash_link}")
        lines.append("")

    if not has_content:
        lines.append("_No changes in this release._")
        lines.append("")

    lines.append(f"_Generated by release-notes-generator on {today}_")
    return "\n".join(lines)


def render_text(commits: list[Commit], version: str) -> str:
    today = date.today().isoformat()
    groups = _group_commits(commits)

    lines = [f"Release {version} — {today}", "=" * 50, ""]

    for key, title in SECTION_ORDER:
        section_commits = groups.get(key, [])
        if not section_commits:
            continue
        lines.append(title)
        lines.append("-" * len(title))
        for c in section_commits:
            scope = f"[{c.scope}] " if c.scope else ""
            issues = " " + " ".join(c.issues) if c.issues else ""
            lines.append(f"  - {scope}{c.subject}{issues}  ({c.short_hash})")
        lines.append("")

    return "\n".join(lines)


def render_json(commits: list[Commit], version: str) -> str:
    groups = _group_commits(commits)
    output = {
        "version": version,
        "date": date.today().isoformat(),
        "sections": {},
        "total_commits": len(commits),
    }
    for key, title in SECTION_ORDER:
        section_commits = groups.get(key, [])
        if section_commits:
            output["sections"][key] = {  # type: ignore[index]
                "title": title,
                "commits": [
                    {
                        "hash": c.short_hash,
                        "scope": c.scope,
                        "subject": c.subject,
                        "author": c.author,
                        "date": c.date,
                        "issues": c.issues,
                        "breaking": c.breaking,
                    }
                    for c in section_commits
                ],
            }
    return json.dumps(output, indent=2)


OutputFormat = Literal["markdown", "text", "json"]


def render(
    commits: list[Commit],
    version: str,
    fmt: OutputFormat = "markdown",
    repo_url: str | None = None,
) -> str:
    if fmt == "markdown":
        return render_markdown(commits, version, repo_url)
    if fmt == "text":
        return render_text(commits, version)
    return render_json(commits, version)
